// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace WorkOrderSystem.Models
{
    public partial class DBLocalKenContext : DbContext
    {
        public DBLocalKenContext()
        {
        }

        public DBLocalKenContext(DbContextOptions<DBLocalKenContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Overtime> Overtime { get; set; }
        public virtual DbSet<WorkingTime> WorkingTime { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Employee>(entity =>
            {
                entity.HasKey(e => e.employee_id)
                    .HasName("PK_Employee_1");

                entity.Property(e => e.employee_id).ValueGeneratedNever();

                entity.Property(e => e.employee_name)
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.gender)
                    .HasMaxLength(20)
                    .IsFixedLength();

                entity.Property(e => e.hire_date).HasColumnType("datetime");
            });

            modelBuilder.Entity<Order>(entity =>
            {
                entity.HasKey(e => e.workorder_code)
                    .HasName("NewTable_PK");

                entity.Property(e => e.workorder_code)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.completionactual_date).HasColumnType("datetime");

                entity.Property(e => e.completiontarget_date).HasColumnType("datetime");

                entity.Property(e => e.pic_name)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.request_date).HasColumnType("datetime");

                entity.Property(e => e.requestor_name)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.work_title)
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Overtime>(entity =>
            {
                entity.HasKey(e => e.overtime_id);

                entity.Property(e => e.overtime_id).ValueGeneratedNever();

                entity.Property(e => e.end_date).HasColumnType("datetime");

                entity.Property(e => e.start_date).HasColumnType("datetime");
            });

            modelBuilder.Entity<WorkingTime>(entity =>
            {
                entity.HasKey(e => e.workingtime_id);

                entity.Property(e => e.workingtime_id).ValueGeneratedNever();

                entity.Property(e => e.end_date).HasColumnType("datetime");

                entity.Property(e => e.start_date).HasColumnType("datetime");
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}