// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WorkOrderSystem.Models;

namespace WorkOrderSystem.Models
{
    public partial interface IDBLocalKenContextProcedures
    {
        Task<List<spPagingOrderResult>> spPagingOrderAsync(OutputParameter<int?> PageIndex, OutputParameter<double?> PageSize, OutputParameter<int?> TotalPages, OutputParameter<double?> RecordCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
