// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkOrderSystem.Models
{
    public partial class Order
    {
        public string workorder_code { get; set; }
        public string work_title { get; set; }
        public string requestor_name { get; set; }
        public DateTime? request_date { get; set; }
        public string pic_name { get; set; }
        public DateTime? completionactual_date { get; set; }
        public DateTime? completiontarget_date { get; set; }
    }
}