// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkOrderSystem.Models
{
    public partial class WorkingTime
    {
        public int workingtime_id { get; set; }
        public int? employee_id { get; set; }
        public DateTime? start_date { get; set; }
        public DateTime? end_date { get; set; }
    }
}